.DEFAULT_GOAL := help
SHELL := /bin/bash

UV ?= uv
COMPOSE ?= docker compose

# ----------------------------------------------------------------------------
# Help
# ----------------------------------------------------------------------------
.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make <target>\n\nTargets:\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

# ----------------------------------------------------------------------------
# Local Python
# ----------------------------------------------------------------------------
.PHONY: install
install: ## Install dependencies into a local .venv via uv
	$(UV) sync --all-groups

.PHONY: lint
lint: ## Ruff lint
	$(UV) run ruff check app tests

.PHONY: fmt
fmt: ## Ruff format + lint --fix
	$(UV) run ruff format app tests
	$(UV) run ruff check --fix app tests

.PHONY: typecheck
typecheck: ## mypy strict on app/
	$(UV) run mypy app

.PHONY: security
security: ## bandit + pip-audit
	$(UV) run bandit -c pyproject.toml -r app
	$(UV) run pip-audit --strict || true

.PHONY: test
test: ## Run the test suite (uses testcontainers, needs Docker)
	$(UV) run pytest --cov --cov-report=term-missing

.PHONY: test-fast
test-fast: ## Run tests without coverage
	$(UV) run pytest -q

# ----------------------------------------------------------------------------
# Database / migrations
# ----------------------------------------------------------------------------
.PHONY: migrate
migrate: ## Apply migrations against $$DATABASE_URL
	$(UV) run alembic upgrade head

.PHONY: revision
revision: ## Create a new autogenerated migration:  make revision m="add foo"
	@test -n "$(m)" || (echo "Usage: make revision m=\"message\""; exit 1)
	$(UV) run alembic revision --autogenerate -m "$(m)"

.PHONY: downgrade
downgrade: ## Step one migration back
	$(UV) run alembic downgrade -1

# ----------------------------------------------------------------------------
# Docker
# ----------------------------------------------------------------------------
.PHONY: up
up: ## Build & start the full stack; tails logs of api
	$(COMPOSE) up --build -d
	@echo "Waiting for api to become ready..."
	@for i in $$(seq 1 30); do \
	  if curl -fsS http://localhost:8000/readyz >/dev/null 2>&1; then \
	    echo "API ready: http://localhost:8000/docs"; exit 0; \
	  fi; sleep 1; \
	done; \
	echo "API did not become ready in time"; $(COMPOSE) logs api; exit 1

.PHONY: down
down: ## Stop the stack
	$(COMPOSE) down -v

.PHONY: logs
logs: ## Tail api logs
	$(COMPOSE) logs -f api

.PHONY: shell
shell: ## Open a shell in the api container
	$(COMPOSE) exec api /bin/bash

.PHONY: seed
seed: ## Insert sample data via scripts/seed.py
	$(COMPOSE) exec api python scripts/seed.py

# ----------------------------------------------------------------------------
# LLM stack (Ollama + chat BFF + UI). Opt-in via Compose profile `llm`.
# ----------------------------------------------------------------------------
.PHONY: llm-up
llm-up: ## Build & start archive + Ollama + chat BFF + UI (first run pulls the model)
	$(COMPOSE) --profile llm up --build -d
	@echo "Waiting for chat BFF to become ready (model pull may take a few minutes on first run)..."
	@for i in $$(seq 1 600); do \
	  if curl -fsS http://localhost:8001/api/health 2>/dev/null | grep -q '"model_ready":true'; then \
	    echo ""; echo "✅ Chat ready: http://localhost:8001"; exit 0; \
	  fi; sleep 2; \
	done; \
	echo ""; echo "Timed out. Check: $(COMPOSE) logs ollama-pull chat"; exit 1

.PHONY: llm-down
llm-down: ## Stop the LLM stack (keeps the model volume so re-up is instant)
	$(COMPOSE) --profile llm down

.PHONY: llm-logs
llm-logs: ## Tail logs of chat + ollama
	$(COMPOSE) --profile llm logs -f chat ollama

.PHONY: llm-purge
llm-purge: ## Stop AND remove the model volume (next llm-up re-pulls)
	$(COMPOSE) --profile llm down -v

# ----------------------------------------------------------------------------
# CI bundle
# ----------------------------------------------------------------------------
.PHONY: ci
ci: lint typecheck security test ## Everything CI runs
